In [1]:
import numpy as np
import scipy.linalg as linalg

from linear_algebra_utils import *
from digraph_algorithms import *
from quiver_pca import *

In [2]:
# Example of augmenting a DAG with a root node
Q = nx.DiGraph()
arrows = [('X', 'Z'), ('Y', 'Z')]
Q.add_edges_from(arrows)


dimensions = {
    'X': 3,
    'Y': 3,
    'Z': 2,
}

bases = construct_standard_bases(dimensions)

nx.set_node_attributes(Q,dimensions,'dimension')
nx.set_node_attributes(Q,bases,'basis')

In [3]:
# Construct linear maps at each edge
rep_maps = {
    ('X', 'Z'): np.array([
        [1.0,0.0,0.0],
        [0.0,1.0,1.0]
    ]),
    ('Y', 'Z'): np.array([
        [1.0,1.0,0.0],
        [0.0,0.0,1.0]
    ])
}
nx.set_edge_attributes(Q,rep_maps,'rep map')

In [4]:
Qplus = augment_DAG_with_root(Q)

In [5]:
generate_space_of_sections(Qplus)

In [6]:
Qplus.nodes['Z']['flow space']

[array([[ 0.        ],
        [-0.57735027],
        [ 0.78867513],
        [ 0.        ],
        [ 0.        ],
        [ 0.21132487]]),
 array([[ 0.57735027],
        [ 0.        ],
        [ 0.        ],
        [ 0.78867513],
        [-0.21132487],
        [ 0.        ]]),
 array([[ 0.57735027],
        [ 0.        ],
        [ 0.        ],
        [-0.21132487],
        [ 0.78867513],
        [ 0.        ]]),
 array([[0.        ],
        [0.57735027],
        [0.21132487],
        [0.        ],
        [0.        ],
        [0.78867513]])]

In [7]:
Qplus.nodes['Z']['flow map']

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0.]])